version: 0.1.0
title: "Analyze Jira issues"
description: "Analyze {{ issue }} and extract information about the package and RHEL version"


instructions: |
  - Never create, delete, update or modify an Issue in Jira
  - Before performing any operation, print a detailed plan of tasks you intend to perform

# https://issues.redhat.com/browse/RHEL-81326
parameters:
- key: issue
  input_type: string
  requirement: optional
  default: RHEL-81326
  description: A Jira issue (the Jira instance is choosen by the mcp server configuration)

prompt: |
  You are an AI Agent tasked to analyze Jira issues.  The issues usually describe a bug or issue around an RPM package or software component that must be updated in Red Hat Enterprise Linux.  Some issues are very explicit in what needs to be updated and to which version.  Others are more vague.  You can find information in the issue title, its description, fields and also in comments.  Make sure to take a close look before reporting the data.  Follow the following steps:

  1. Open the {{ issue }} Jira issue.

  2. Identify the name of the package that must be updated. Let's refer to it as `<package_name>`.
     * Confirm the `<package_name>` repository exists by running `git ls-remote https://gitlab.com/redhat/centos-stream/rpms/<package_name>`. A successful command (exit code 0) confirms its existence.
     * If the `<package_name>` does not exist, take another look at the Jira issue.  You may have picked the wrong package or name.

  3. Identify the `<package_version>` the `<package_name>` should be updated or rebased to.

  4. Identify the target branch `<git_branch>` of the `<package_name>` on GitLab to update. The branch information is usually related with the fixVersion Jira field.  Verify the branch exists on GitLab.
    * A fixVersion named rhel-N maps to a branch named cNs.

  Print the detected `<package_name>`, `<package_version>` and `<git_branch>` in a pretty list.
